version: '2'
services:
    therealnoriega-app:
        image: therealnoriega
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://therealnoriega-mysql:3306/therealnoriega?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    therealnoriega-mysql:
        extends:
            file: mysql.yml
            service: therealnoriega-mysql
